tag: a-HfO2
train_folder: '../../../Amorphous-Hamiltonians/HfO2_2/'
val_folder: '../../../Amorphous-Hamiltonians/HfO2_1/'
test_folder: '../../../Amorphous-Hamiltonians/HfO2_3/'

train_start: -1
train_total_length: 54
train_num_slices: 18
train_slice_direction: 0 # 0 for x, 1 for y, 2 for z direction of slicing

val_start: 25
val_total_length: 4
val_slice_direction: 0 # 0 for x, 1 for y, 2 for z direction of slicing

test_start: -1
test_total_length: 60
test_num_slices: 1
test_slice_direction: 0 # 0 for x, 1 for y, 2 for z direction of slicing


lmax: 4
mmax: 4
orbital_basis: 'SZV'


train_cell:  #None means that cell is rectangular, contains the lattice vectors of the cell
val_cell:  #same parameter but for validation structure
test_cell:  #same parameter but for test structure
atom_orbitals: {'8':[0,1], '72':[0,0,1,2]}
orbital_types: [[0,1],[0,0,1,2]]
rcut: 4
